### ISSUE TITLE
Problem running makediary

### ISSUE THREAD

**Issue by sshelagh** [russells/makediary#2]
shelagh@Gorgon:~$ geoffdiary 
Traceback (most recent call last):
  File "/usr/bin/makediary", line 5, in <module>
    from makediary import makediary
  File "/usr/local/lib/python2.7/dist-packages/makediary/makediary.py", line 17, in <module>
    from PostscriptPage          import PostscriptPage
  File "/usr/local/lib/python2.7/dist-packages/makediary/PostscriptPage.py", line 4, in <module>
    import EpsImagePlugin

My usual strategy is to splatter install. But I need help to work out what's missing. 

ImportError: No module named EpsImagePlugin

**Comment by sshelagh** [comment]
Doing some more research I think I might have some $path issues with Python.

**Comment by russells** [comment]
Sorry, I missed the opening of this issue.  (I should have received an email, I guess, but can't find it.)

Now you've closed the issue.  Does that mean makediary works for you?

**Comment by sshelagh** [comment]
Hi Russell,

No, actually I haven't worked out why makediary can't find
EpsImageModule.py  I obviously have some kind of path problem with python
on my system but really haven't had time to work out how to fix it.

It may be because I have both python2.7 and python3 and things might be
confused. But I could use some pointers I guess. If it is a matter of
assuming my su powers and copying directories around to make it work I will
do that. I use makediary to make christmas present for my husband, so I
have a time limit.

I am on Ubuntu 14.04 if that information helps.

Cheers

Shelagh

Shelagh

**Comment by russells** [comment]
Could you run `python -V` to make sure you're running python 2 (probably 2.7.6)?

Ensure you have the `python-imaging-compat` package installed.

Then try

    export PYTHONPATH=/usr/lib/python2.7/dist-packages/PIL
    geoffdiary

I assume `geoffdiary` is a wrapper around `makediary` with arguments.

I haven't looked at makediary code for a while, and it looks like there have been some changes to the way the python imaging library works, at least on Ubuntu.

**Comment by sshelagh** [comment]
Hi Russell,

Setting the python environment did help in that it get further into the
script. Taking out all images for the moment did the trick. At least I have
a diary. I can do the images as a separate page later.

I will keep fiddling to see if I can make it work with pictures. Of course
that is probably beyond my programming chops. But can't hurt to try.

Thanks for your help.

Shelagh

**Comment by russells** [comment]
Why did you have to take the images out?  What output did you get when you set PYTHONPATH and left the images in?

**Comment by sshelagh** [comment]
I will sit down tomorrow and spend a bit of time sorting this out.

Cheers

Shelagh

**Comment by sshelagh** [comment]
shelagh@Gorgon:~$ export PYTHONPATH=/usr/lib/python2.7/dist-packages/PIL
shelagh@Gorgon:~$ geoffdiary
Traceback (most recent call last):
  File "/usr/bin/makediary", line 8, in <module>
    makediary.go(sys.argv[0], sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/makediary/makediary.py", line 197,
in go
    d.diary()
  File "/usr/lib/python2.7/dist-packages/makediary/makediary.py", line 51,
in diary
    w( CoverPage(di).page() )
  File "/usr/lib/python2.7/dist-packages/makediary/BasicPostscriptPage.py",
line 90, in page
    return self.preamble + self.body() + self.postamble
  File "/usr/lib/python2.7/dist-packages/makediary/CoverPage.py", line 117,
in body
    + self.image(self.di.coverImage,picleft,picbottom,picxsize,picysize)
  File "/usr/lib/python2.7/dist-packages/makediary/PostscriptPage.py", line
23, in image
    im = Image.open(file,"r")
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 2028, in open
    raise IOError("cannot identify image file")
IOError: cannot identify image file
shelagh@Gorgon:~$

shelagh@Gorgon:~$ cat ~/bin/geoffdiary
#!/bin/bash
#geoffdiary utility to make a postscript diary for Geoff.
# using pstopdf is a better option than ps2pdf as the paper size is
honoured. ps2pdf must use the /etc/paper setting.
PCAL_DIR=/home/shelagh


Cat of the wrapper script.

I checked all the files and the names and places are correct.

/usr/bin/makediary\
 --pcal --pcal-planner\
 --page-size=a5\
 --paper-size=a5 --layout=day-to-page --line-spacing=4.25\
 --moon\
 --cover-image=/home/shelagh/Pictures/motorbike.jpg\
 --image-page=/home/shelagh/Pictures/Shelagh.jpg\
 --image-page=/home/shelagh/Pictures/Gavin.jpg\
 --image-page=/home/shelagh/Pictures/Kellen.jpg\
 --weeks-after=2 --weeks-before=0 --appointments --appointment-width=30%\
 --notes-pages=8 --colour\
 --output=gdiary-$(date --date='1 year' +%Y).ps
shelagh@Gorgon:~$

**Comment by sshelagh** [comment]
I searched on the phrase File
"/usr/lib/python2.7/dist-packages/PIL/Image.py", line 2028, in open
    raise IOError("cannot identify image file")

The easiest to understand entry was
http://uzzai.com/Wj03Alx8/how-to-open-a-simple-image-using-streams-in-pillowpython.html

Something about stringio and buff.seek(0) before loading file but when I
had a poke around in makediary's file PostscriptFile.py seems the most
likely candidate but I can't work out where the extra code should go.

Is there any other thing I can do to help debug this?


Cheers

Shelagh

**Comment by sshelagh** [comment]
I still can't work out why images won't print. Let me know if there is any more I can do to debug this.

**Comment by russells** [comment]
I didn't get the notifications for your earlier comments, sorry.  It may have been because the issue was closed, as I got notified when you reopened it and commented after that.

Looks like a problem with one or more of your images.

Can you do these:

    ls -l /home/shelagh/Pictures/motorbike.jpg /home/shelagh/Pictures/Shelagh.jpg /home/shelagh/Pictures/Gavin.jpg /home/shelagh/Pictures/Kellen.jpg
    file /home/shelagh/Pictures/motorbike.jpg /home/shelagh/Pictures/Shelagh.jpg /home/shelagh/Pictures/Gavin.jpg /home/shelagh/Pictures/Kellen.jpg

and copy in the output.

**Comment by russells** [comment]
Oh, I've assumed there aren't any other images being included, say from a `.calendar` file.  Are there any other images?  If there are, please do the same for those images (`ls -l` and `file`.)

**Comment by sshelagh** [comment]
No images from a .calendar file.

shelagh@Gorgon:~$ file /home/shelagh/Pictures/motorbike.jpg /home/shelagh/Pictures/Shelagh.jpg /home/shelagh/Pictures/Gavin.jpg /home/shelagh/Pictures/Kellen.jpgShelagh.jpg /home/shelagh/Pictures/Gavin.jpg /home/shelagh/Pictures/Kellen.jp/home/shelagh/Pictures/motorbike.jpg: JPEG image data, EXIF standard 2.2
/home/shelagh/Pictures/Shelagh.jpg:   JPEG image data, JFIF standard 1.01
/home/shelagh/Pictures/Gavin.jpg:     JPEG image data, JFIF standard 1.01
/home/shelagh/Pictures/Kellen.jpg:    JPEG image data, JFIF standard 1.01
shelagh@Gorgon:~$ ls -l /home/shelagh/Pictures/motorbike.jpg /home/shelagh/Pictures/Shelagh.jpg /home/shelagh/Pictures/Gavin.jpg /home/shelagh/Pictures/Kellen.jpg
-rwxr-xr-x 1 shelagh shelagh   27712 Dec 23  2006 /home/shelagh/Pictures/Gavin.jpg
-rwxr-xr-x 1 shelagh shelagh   12874 Nov 19  2012 /home/shelagh/Pictures/Kellen.jpg
-rwxr-xr-x 1 shelagh shelagh 1864173 Apr 18  2008 /home/shelagh/Pictures/motorbike.jpg
-rw-r--r-- 1 shelagh shelagh   80204 Jan 14  2010 /home/shelagh/Pictures/Shelagh.jpg

**Comment by sshelagh** [comment]
I changed one of the images to an eps format. That one does not cause problems. But of course changing all the files to eps (which looks weird in any case) is not really the answer.

**Comment by russells** [comment]
Did you change motorbike.jpg?  That has a slightly different output from file.  Would it be ok to send me that file?

**Comment by sshelagh** [comment]
I changed the permissions on it but I just checked and it still shows

shelagh@Gorgon:~$ file /home/shelagh/Pictures/motorbike.jpg
/home/shelagh/Pictures/Shelagh.jpg /home/shelagh/Pictures/Gavin.jpg
/home/shelagh/Pictures/Kellen.jpg
/home/shelagh/Pictures/motorbike.jpg: JPEG image data, EXIF standard 2.2
/home/shelagh/Pictures/Shelagh.jpg:   JPEG image data, JFIF standard 1.01
/home/shelagh/Pictures/Gavin.jpg:     JPEG image data, JFIF standard 1.01
/home/shelagh/Pictures/Kellen.jpg:    JPEG image data, JFIF standard 1.01

I've attached the photo.

**Comment by russells** [comment]
I can't see the photo, either in github or in the email from github.

**Comment by sshelagh** [comment]
Did you see the photo yet? I uploaded it again.

**Comment by russells** [comment]
No, sorry.  Do you see it when you view this issue?  If so, where do you see it?

**Comment by sshelagh** [comment]
I see it as a link, not the full picture. But when I click on the link it opens in the browser.
https://cloud.githubusercontent.com/assets/168074/11585882/47edd24e-9ac3-11e5-8392-5343a592f8f5.jpg 

I tried opening the files in the python console, using the tutorial examples as my guide and all my images opened fine. What does the "r" in Image.open("file.jpg","r") mean? It mentions a mode in the documentation but not what it does. Is is short for read?

**Comment by russells** [comment]
Got it.  Thanks.  The link's there now, too.  It may have been there before, but I don't remember it.

Anyway, the image itself is fine, but now I see this on Ubuntu (python-pil 2.3.0-1ubuntu3) but not on Debian (python-pil 2.6.1-2):

    $ ./makediary/makediary.py --cover-page-image=sshelagh-motorbike.jpg 
    Traceback (most recent call last):
      File "./makediary/makediary.py", line 205, in <module>
        go(sys.argv[0], sys.argv[1:])
      File "./makediary/makediary.py", line 197, in go
        d.diary()
      File "./makediary/makediary.py", line 51, in diary
        w( CoverPage(di).page() )
      File "/home/russells/src/makediary/makediary/BasicPostscriptPage.py", line 90, in page
        return self.preamble + self.body() + self.postamble
      File "/home/russells/src/makediary/makediary/CoverPage.py", line 31, in body
        s += self.image(self.di.coverPageImage, l, b, w, h)
      File "/home/russells/src/makediary/makediary/PostscriptPage.py", line 77, in image
        EpsImagePlugin._save(im,epsfile,None,1)
      File "/usr/lib/python2.7/dist-packages/PIL/EpsImagePlugin.py", line 360, in _save
        fp = io.TextIOWrapper(NoCloseStream(fp), encoding='latin-1')
    AttributeError: readable
    $

Is that what you see now?

It may be this: https://github.com/python-pillow/Pillow/issues/470, which is fixed in python-pil 2.4.0.  Ubuntu vivid (15.04) has a later python-pil, but I don't like telling people to update the entire OS to fix something like this.

More thought required...

**Comment by sshelagh** [comment]
I see it as a link, not the full picture. But when I click on the link it opens in the browser.
https://cloud.githubusercontent.com/assets/168074/11585882/47edd24e-9ac3-11e5-8392-5343a592f8f5.jpg 

I tried opening the files in the python console, using the tutorial examples as my guide and all my images opened fine. What does the "r" in Image.open("file.jpg","r") mean? It mentions a mode in the documentation but not what it does. Is is short for read?

**Comment by sshelagh** [comment]
There may be a PPA with an updated PIL library. I might just lodge a bug against it in 14.04 if there isn't already one.

**Comment by russells** [comment]
The "r" in Image.open("file.jpg","r") means to open read only.

**Comment by sshelagh** [comment]
I found a ppa @ https://launchpad.net/~chris-lea/+archive/ubuntu/python-pil that is more up to date. 
I changed postscriptPage.py to read 
from PIL import Image
and the diary builds great now with the pictures.
Thank you for your patience.
